### ISSUE TITLE
Simulator hangs on startup when existing device file is present

### ISSUE THREAD

**Issue by amprim** [uhppoted/uhppote-simulator#6] opened 2022-10-14 13:31 UTC
As mentioned in #5. 

---

## Issue

When running `uhppote-simulator`, the simulator hangs when attempting to load config files from a previous run. Neither the REST API or any simulated controllers can be contacted.

Issue encountered on Linux x86_64 (PopOS/Ubuntu 22.04 LTS).

## Steps to Reproduce

In a terminal window, run the following to start a `uhppote-simulator` instance.

```
./uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/
```

In another terminal window, run the following to generate a controller config. (EDIT: Fixed duplicate command)

```
curl -X POST http://127.0.0.1:8000/uhppote/simulator -H 'Content-Type: application/json' -d '{"device-id": 123456789, "device-type": "UT0311-L04", "compressed": false}'
```

In the first terminal window, stop and rerun the `uhppote-simulator` command. It will hang similar to the following. The `make` targets were setup to make testing easier: `simulator` checks for and removes a config file prior to running the simulator, while `sim` does not, just attempts to run the simulator.

```
amprim@pop-os:~/Projects/access_control$ make simulator
mkdir -p /tmp/devices
./uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/devices
   ... loading devices from '/tmp/devices'
   ... bound to address '127.0.0.1:60000'

^CFailed to read from UDP socket [read udp 127.0.0.1:60000: use of closed network connection]
make: *** [Makefile:7: simulator] Error 1

amprim@pop-os:~/Projects/access_control$ make sim
./uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/devices
   ... loading devices from '/tmp/devices'
```

As you can see, something prevents the simulator from reaching the point of binding to the `--bind` address.

---

Thank you in advance for your assistance!

**Comment by uhppoted** [comment] 2022-10-14 16:23
Hi,

I can't seem to reproduce your problem - when I try this is what I get:

_In first terminal:_
```
>> .. running simulator 1
mkdir -p /tmp/devices
./bin/uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/devices
   ... loading devices from '/tmp/devices'
   ... bound to address '127.0.0.1:60000'
```
_In second terminal:_
```
>> .. running simulator 2
./bin/uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/devices
   ... loading devices from '/tmp/devices'
Failed to bind to UDP socket [listen udp 127.0.0.1:60000: bind: address already in use]
uhppoted@uhppoted:/opt/uhppoted/uhppote-simulator$ 
```
Which is as expected - you can't have two simulators running at the same time because they both bind to the same _address:port_.

Am I missing something?

BTW, _Docker_ may be an easier way to achieve what I think you're trying to do - there's an example [here](https://github.com/uhppoted/uhppoted/tree/master/docker/simulator).

**Comment by amprim** [comment] 2022-10-14 22:43
Oh, d'oh! I didn't copy the second command correctly, it's not supposed to be the same as the first. Fixed above, sorry about that!

That said, I just attempted to reproduce this again, and it's started working correctly, at least when I run the commands directly from terminal. Let me do a little more digging and see if I can figure out what triggers this.

**Comment by uhppoted** [comment] 2022-10-14 22:44
Ah, ok - was able to replicate this with your configuration and scripts from [Possible issue with time profiles](https://github.com/uhppoted/uhppote-simulator/issues/5). Just to confirm - these are the steps I followed:

1. Clean out the _tmp_ folder
```
rm -f /tmp/123456789.json
```
2. Run one copy of the simulator:
```
./bin/uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/

>   ... loading devices from '/tmp/'
>   ... bound to address '127.0.0.1:60000'
```
3. Run the CLI test program to create a _/tmp/123456789.json_ file:
```
./test-cli.sh

> 123456789: time profile 3 created
> 123456789: time profile 2 created
> 123456789 154321 true
> 123456789 112345 true
...

```
4. Run a second copy of the simulator in a different window:
```
./bin/uhppote-simulator --bind 127.0.0.1:60000 --rest 127.0.0.1:8000 --devices /tmp/
>    ... loading devices from '/tmp/'

```

Because both copies of the simulator bind to the same UDP and TCP _address:ports_ this isn't going to work - it should however at least fail with a useful error. Let me dig into that..

**Comment by amprim** [comment] 2022-10-14 22:53
Yup, that looks right.

I think it may be an issue with either card swipe events, or events in general, being written to/read from the file. Removing lines from `test-cli.sh`, the issue starts occurring after the first cURL call to the `swipe` REST endpoint.

**Comment by twystd** [comment] 2022-10-14 23:29
Yup, it's an actual bug - somehow the _JSON_ device file is getting serialized with an event list that looks like this:
```
  "events": {
    "size": 0,
    "chunk": 0,
    "index": 0,
    "events": [
      {
        "index": 1,
        "type": 2,
        "granted": true,
       ...
```
which triggers another bug in the [deserialisation](https://github.com/uhppoted/uhppote-simulator/blob/master/entities/events.go#L138-L140) where it attempts to truncate the event list to the correct size:
```
...
	for len(l.events) > int(l.size) {
		l.events = l.events[l.chunk:]
	}
...
```
 It can be reproduced with just one instance of the simulator and the _test-cli.sh_ script.

**Comment by uhppoted** [comment] 2022-10-15 00:05
The `EventList` wasn't being initialised correctly when unmarshalling a JSON file - I've pushed a partial fix to the master branch which does do the initialisation.

Hopefully that should sort out your immediate problem - I still need to take a look at the logic behind the infinite loop (it's been a while) and in general make this more robust.

**Comment by amprim** [comment] 2022-10-15 00:21
Yup, that fixed it. The simulator now fully loads when a previous device file is loaded.

**Comment by uhppoted** [comment] 2022-10-15 17:35
Ok, root cause was that the events list was not initialised in the simulator default constructor, which is how it ended up with:
```
"events": {
    "size": 0,
    "chunk": 0,
...
```
Have fixed that and also:
- used reasonable defaults if for some reason the size or the chunk is zero
- reworked trimming the events list to use truncation rather than a loop 

Think that fixes this in a way that I'm happy with - will leave this open for another day or two in case anything related crops up.

**Comment by uhppoted** [comment] 2022-10-18 23:49
Closing this as fixed - feel free to reopen if you need to :-)

**Closed by uhppoted** 2022-10-18 23:49 UTC
